#!/bin/sh

BEGIN INIT INFO
Provides: SageTea Server 64 Bit Squeak Portal
Required-Start: $network $postgresql
Required-Stop: $network $postgresql
Default-Start: 2 3 4 5
Default-Stop: 0 1 6
Short-Description: SageTea Server 64 Bit Squeak Portal
Description: SageTea Server 64 Bit Squeak Portal on %i
END INIT INFO
PORTAL_CONF="/home/%i/portal.conf"

if [ ! -f "$PORTAL_CONF" ]; then
echo "The file $PORTAL_CONF does not exist."
exit 1
fi

case "$1" in
start)
su - %i -c "cd /home/%i && /opt/sageteacloudsq/SqueakVM/squeak -nodisplay -nosound -encoding UTF-8 /opt/sageteacloudsq/SageTeaCloud.image -cwd /home/%i -doit 'SageTeaManager startServerLogging; launch'"
;;
stop)
# Not provided in the original script
;;
restart)
su - %i -c "cd /home/%i && /opt/sageteacloudsq/SqueakVM/squeak -nodisplay -nosound -encoding UTF-8 /opt/sageteacloudsq/SageTeaCloud.image -cwd /home/%i -doit 'SageTeaManager startServerLogging; launch'"
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
;;
esac

exit 0