name: Build and Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  Build:
    runs-on: mcr.microsoft.com/windows/servercore
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sagetea
          password: dckr_pat_pDqQB441UonwLPfYZgqNWPpk2bw
      -
        name: Build Windows
        uses: docker/build-push-action@v3
        with:
          context: .
          file: /home/runner/work/SageTeaWorkStation/SageTeaWorkStation/Dockerfile
          platforms: windows/amd64
          push: true
          tags: sagetea/sageteaworkstation:dev
